name: Deploy to Umbler

on:
  push:
    branches:
      - main # ou a branch que você usa para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Envia arquivos para Umbler via API
        uses: umbler/deploy-action@v1.0.0
        with:
          api_key: ${{ secrets.UMBLER_API_KEY }}
          site: ${{ secrets.UMBLER_SITE }}
          email: ${{ secrets.UMBLER_EMAIL }}
          dir: Tijucas-Open
